apiVersion: 1

policies:
  - orgId: 1
    receiver: slack-critical
    continue: true
    routes:
      - receiver: slack-critical
        matchers:
          - severity = critical
        continue: false
      - receiver: slack-warning
        matchers:
          - severity = warning
        continue: false
      - receiver: slack-info
        matchers:
          - severity = info
        continue: false

